<a href="https://colab.research.google.com/github/shivam0070/python-code/blob/main/Geeks_for_Geeks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basic Programs:**

**1.)Question**

In [ ]:
#Python program to add two numbers
num1 = 15
num2 = 12
  
# Adding two nos
sum = num1 + num2
print(sum)

27


In [ ]:
#2
number1 = input("First number: ")
number2 = input("\nSecond number: ")
  
# Adding two numbers
# User might also enter float numbers
sum = float(number1) + float(number2)
print(sum)

First number: 5

Second number: 5
10.0


In [ ]:
#3
if __name__ == "__main__" :
    
  num1 = 15
  num2 = 12
    
  # Adding two numbers
  sum_twoNum = lambda num1, num2 : num1 + num2
    
  # printing values
  print(sum_twoNum)

<function <lambda> at 0x7f69490e8ca0>


In [ ]:
##To define a function that take two integers and return the sum of those two numbers
def add(a,b):
  return a+b
  
#initializing the variables
num1 = 10
num2 = 5
  
#function calling and store the result into sum_of_twonumbers
sum_of_twonumbers = add(num1,num2)
print(sum_of_twonumbers)

15


**2.) Question**

In [ ]:
#Maximum of two numbers in Python
def Maximum(a, b):
  if a >= b:
    return a
  else:
    return b
a = 2
b = 3
print(Maximum(a,b))


3


In [ ]:
#2
a = 2
b = 3
maximum = max(a,b)
print(maximum)

3


In [ ]:
# find max num using sort method
a = 2
b = 5
x = [a,b]
x.sort()
print(x[-1])

5


**3.)Question**

In [ ]:
# factorial of given number
def factorial(n):
  return 1 if (n==1 or n==0) else n * factorial(n-1)
num = 5
print("Factorial of",num,"is",factorial(num))

Factorial of 5 is 120


In [ ]:
#2
import math
def factorial(n):
  return(math.factorial(n))
num = 5 
print("factorial of",num,"is",factorial(num))

factorial of 5 is 120


In [ ]:
#3
import numpy
n=5
x=numpy.prod([i for i in range(1,n+1)])
print(x)

120


**4.) Question**


In [ ]:
## Python3 program to find simple interest
P = int(input("Enter the principal amount :"))
T = int(input("Enter the time period :"))
R = int(input("Enter the rate of interest :"))

si = (P * T * R)/100
print('The Simple Interest is', si)


Enter the principal amount :100
Enter the time period :2
Enter the rate of interest :10
The Simple Interest is 20.0


**5.) Question**

In [ ]:
# Python3 program to find compound
# interest for given values.
p= 1200    
t= 2      
r= 5.4     
a=p*(1+(r/100))**t   
ci=a-p   
print(ci)

133.0992000000001


In [ ]:
#2
def compound_interest(principal, rate, time):
    Amount = principal
    for i in range(time):
        Amount = Amount * (1 + rate/100)
    CI = Amount - principal
    print("Compound interest is", CI)
# Driver Code
compound_interest(1200, 10, 2)

Compound interest is 252.00000000000023


***6.) Question***

In [ ]:
# check number is armstrong or not, armstrong means -- 153 is an Armstrong number.
#1*1*1 + 5*5*5 + 3*3*3 = 153
n = 153
s = n
b = len(str(n))
sum1 = 0
while n != 0:
  r = n % 10
  sum1 = sum1+(r**b)
  n = n//10
if s == sum1:
  print("the given number", s, "is armstrong number")
else:
  print("the given number", s, "is not armstrong number")


the given number 153 is armstrong number


**7.) Question**

In [ ]:
# Python program to find Area of a circle
def findArea(r):
    PI = 3.142
    return PI * (r*r);
 
print("Area is %.6f" % findArea(5));

Area is 78.550000


**8.) Question**

In [ ]:
# Python program to print all
# prime number in an interval
lower_value = int(input ("Please, Enter the Lowest Range Value: "))  
upper_value = int(input ("Please, Enter the Upper Range Value: "))  
  
print ("The Prime Numbers in the range are: ")  
for number in range (lower_value, upper_value + 1):  
    if number > 1:  
        for i in range (2, number):  
            if (number % i) == 0:  
                break  
        else:  
            print (number)  


Please, Enter the Lowest Range Value: 5
Please, Enter the Upper Range Value: 20
The Prime Numbers in the range are: 
5
7
11
13
17
19


In [ ]:
n=int(input("enter the number"))
if n <2:
  print("not a prime no")
else:
  for i in range(2,n):
    if n%i==0:
      print("not a prime no")
      break
    else:
      print("its a prime no")

enter the number4
not a prime no


**9.) Question**

In [ ]:
#Python Program to Check Prime Number
num = 11
if num > 1:
  for i in range(2, int(num/2)+1):
    if (num%i) == 0:
      print(num, "is not a prime number")
      break
  else:
    print(num, "is a prime number")
else:
  print(num, "is not a prime number")

11 is a prime number


**10.) Question**

In [ ]:
# Function for nth Fibonacci numbe=0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377।
def Fibonacci(n):
  if n<= 0:
    print("Incorrect input")
     
  elif n == 1: #first fibonacci number is 0
    return 0
     
  elif n == 2:#second fibonacci number is 1
    return 1
  else:
    return Fibonacci(n-1)+Fibonacci(n-2)
print(Fibonacci(10))

34


In [ ]:
#how to check if a given number is fibonacci number or not
 
import math
 
def isPerfectSquare(x):
    s = int(math.sqrt(x))
    return s*s == x
 
def isFibonacci(n):
  
    return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4)

for i in range(1, 11):
    if (isFibonacci(i) == True):
        print(i, "is a Fibonacci Number")
    else:
        print(i, "is a not Fibonacci Number ")

1 is a Fibonacci Number
2 is a Fibonacci Number
3 is a Fibonacci Number
4 is a not Fibonacci Number 
5 is a Fibonacci Number
6 is a not Fibonacci Number 
7 is a not Fibonacci Number 
8 is a Fibonacci Number
9 is a not Fibonacci Number 
10 is a not Fibonacci Number 


In [ ]:
# Python Program to find position of n\'th multiple
# of a number k in Fibonacci Series
 
def findPosition(k, n):
    f1 = 0
    f2 = 1
    i =2;
    while i!=0:
        f3 = f1 + f2;
        f1 = f2;
        f2 = f3;
 
        if f2%k == 0:
            return n*i
 
        i+=1
         
    return
 
k = 4;
 
print("Position of n\'th multiple of k in Fibonacci Series is", findPosition(k,n));
 

NameError: ignored

In [ ]:
#Program to print ASCII Value of a character

In [ ]:
#sum of squares first n natural numbers
n=int(input("enter the number"))
sum=0
for i in range(1,n+1):

  sum +=i**2
print("the sum of squares of first", n, "natural number is", sum)

enter the number2
the sum of squares of first 2 natural number is 5


In [ ]:
#sum of cube first n natural numbers
n=int(input("enter the number"))
sum=0
for i in range(1,n+1):

  sum +=i**3
print("the sum of cube of first", n, "natural number is", sum)

the sum of cube of first 3 natural number is 36


# **ARRAY**

In [ ]:
#find sum of array
list1 = [12, 3, 4, 15] 
ans = sum(list1)
print("sum of array:" , ans)
 

sum of array: 34


In [ ]:
## Python3 program to find maximum
# in arr[] of size n
def largest(arr, n):
  arr.sort()
  return arr[n-1]
arr = [10,23,4,432,443]
n= len(arr)
Ans = largest(arr, n)
print("Largest in given array ", Ans)

Largest in given array  443


In [ ]:
# Python program using the List
# slicing approach to rotate the array
def rotatelist(arr,d,n):
  arr[:]=arr[d:n]+arr[0:d]
  return arr
arr = [2,4,6,7,8]
print(arr)
print("Rotated list is")
print(rotatelist(arr,2,len(arr)))
  

[2, 4, 6, 7, 8]
Rotated list is
[6, 7, 8, 2, 4]


In [ ]:
#Reversal algorithm for array rotation
def leftRotate(arr, d):
    n = len(arr)
    rverseArray(arr, 0, d-1)
    rverseArray(arr, d, n-1)  #doubt
    rverseArray(arr, 0, n-1)

In [ ]:
#split the array and add the first part to the end
def splitArr(a, n, k):
  b = a[:k]
  return (a[k::]+b[::])
arr = [12,10,2,4,55,66,69]
n=len(arr)
position=2
arr = splitArr(arr, n, position)
for i in range(0,n):
  print(arr[i], end=' ')

2 4 55 66 69 12 10 

In [ ]:
#find remainder of array multiplication diveded by n
arr = [100, 10, 5, 25, 35, 14];lens = len(arr);n = 11
mul = 1
for i in range(lens):
  mul = (mul * (arr[i]%n)) % n
print(mul % n)

9


In [ ]:
#check if given array is monotonic
def isMonotonic(A):
    x, y = [], []
    x.extend(A)
    y.extend(A)
    x.sort()
    y.sort(reverse=True)
    if(x == A or y == A):
        return True
    return False
 
 
# Driver program
A = [6, 5, 4, 4]
 
# Print required result
print(isMonotonic(A))

True


# **LIST PROGRAMS:**

In [ ]:
#   swap first and last element of a list
list = [1,2,3,4,5]
list[0],list[-1] = list[-1],list[0]
print(list)

[5, 2, 3, 4, 1]


In [ ]:
#Python program to swap two elements in a list
list1 = [23, 65, 19, 90]
pos1,pos2 = 2,3
list1[pos1],list1[pos2]=list1[pos2],list1[pos1]
print(list1)

[23, 65, 90, 19]


In [ ]:
#Ways to find length of list
list2 =len([23, 65, 19, 90])
 
print("The length of list is: ", list2)

 

The length of list is:  4


In [ ]:
a = []
a.append("Hello")
a.append("Geeks")
a.append("For")
a.append("Geeks")
print("The length of list is: ", len(a))

The length of list is:  4


In [ ]:
#Check if element exists in list in Python
lst=[ 1, 6, 3, 5, 3, 4 ]
i=7
if i in lst:
  print("exist")
else:
  print("not exist")

not exist


In [ ]:
#Different ways to clear a list in Python
geek = [2,3,5,6]
print("geek before clear: ", geek)
geek.clear()
print("geek after clear: ", geek)

geek before clear:  [2, 3, 5, 6]
geek after clear:  []


In [ ]:
#reverse list
lis =  [1, 2, 3, 4, 5]
print(list[::-1])

[1, 4, 3, 2, 5]


In [ ]:
#find sum of element
lst1 = [11, 5, 17, 18, 23]
total = sum(lst1)
print("sum of all elements in given list:", total)

sum of all elements in given list: 74


In [ ]:
# Python program to find sum of elements in list
  
total = 0
  
# creating a list
list1 = [11, 5, 17, 18, 23]
  
# Iterate each element in list
# and add them in variable total
for ele in range(0, len(list1)):
    total = total + list1[ele]
  
# printing total value
print("Sum of all elements in given list: ", total)

Sum of all elements in given list:  74


In [ ]:
#multiply number in list
import numpy
x = [1,2,4]
y = [6,7,8]
#using numpy.pord() to get the multiplications
result1 = numpy.prod(x)
result2 = numpy.prod(y)
print(result1)
print(result2)

8
336


In [ ]:
#find smallest number in list
a = [10, 20, 4, 45, 99]
a.sort()
print("smallest elemtn is: ", a[0])

smallest elemtn is:  4


In [ ]:
#find largest number in list
a = [10, 20, 4, 45, 99]
a.sort()
print("largest elemnt is : ",a[-1])

largest elemnt is :  99


In [ ]:
#find 2nd largest number in list
a = [10, 20, 4, 45, 99]
a.sort()
print("largest element is: ",a[-2])

largest element is:  45


In [ ]:
#find N largest elements from a list
l = [1000, 298, 3579, 100, 200, -45, 900]
n = 4
l.sort()
print(l[-n:])

[298, 900, 1000, 3579]


In [ ]:
#find even num
list1 = [10, 21, 4, 45, 66, 93]
for num in list1:
  if num % 2 ==0:
    print(num, end=" ")

10 4 66 

In [ ]:
##find all even num in range
n=int(input("enter the number"))
for i in range(n,0,-1):
  print(i*2,end=' ')
  

enter the number8
16 14 12 10 8 6 4 2 

In [ ]:
# Python program to print odd Numbers in a List
 
list1 = [10, 21, 4, 45, 66, 93]
 
for num in list1:
 
    if num % 2 != 0:
       print(num, end=" ")

21 45 93 

In [ ]:
# Python program to print all odd Numbers in range in a List
n=int(input("enter number: "))
for i in range(n,0,-1):
  print(i*2-1,end=' ')

enter number: 8
15 13 11 9 7 5 3 1 

In [ ]:
#print positive numbers in a list
list1 = [10, 21, -4, -45, 66, 93]
print("original numbers in the list: ",list1)
print("positive numbers in the said list: ")
for num in list1:
  if num > 0:
    print(num, end = " ")

 
 
 
     

original numbers in the list:  [10, 21, -4, -45, 66, 93]
positive numbers in the said list: 
10 21 66 93 

In [ ]:
#print all negative numbers in a range
list1 = [10, 21, -4, -45, 66, 93]
print("original numbers in the list: ",list1)
print("Negative numbers in the said list: ")
for num in list1:
  if num < 0:
    print(num, end = " ")


original numbers in the list:  [10, 21, -4, -45, 66, 93]
Negative numbers in the said list: 
-4 -45 

In [ ]:
#Remove multiple elements from a list in Python
list1 = [11, 5, 17, 18, 23, 50] 
for ele in list1:
  if ele % 2 == 0:
    list1.remove(ele)
    print("new list after removing all even numbers: ", list1)

new list after removing all even numbers:  [11, 5, 17, 23, 50]
new list after removing all even numbers:  [11, 5, 17, 23]


In [ ]:
list1 = [11, 5, 17, 18, 23, 50] 
for ele in list1:
  if ele%2 != 0:
    list1.remove(ele)
    print("new list after removing all even numbers ", list1)

new list after removing all even numbers  [5, 17, 18, 23, 50]
new list after removing all even numbers  [5, 18, 23, 50]
new list after removing all even numbers  [5, 18, 50]


In [ ]:
#Remove empty List from List
test_list = [5, 6, [], 3, [], [], 9]
print("the original list is : "+ str(test_list))
 
[ele for ele in test_list if ele != []]
print("list after empty list removal: " + str(res))

the original list is : [5, 6, [], 3, [], [], 9]
list after empty list removal: [5, 6, 3, 9]


In [ ]:
#Python | Cloning or Copying a list

import copy
li1 = [1, 2, [3,5], 4]
li3 = copy.deepcopy(li1)
print(li3)

[1, 2, [3, 5], 4]


In [ ]:
# Count occurrences of an element in a list
list2 = [3,3,3,3,56,7765,54,434,3,65]
list2.count(3)

5

In [ ]:
#Remove empty tuples from a list
tuples = [(), ('ram', '15', '8'), (), ('laxman', 'sita'),
          ('krishna', 'akbar', '45'), ('', ''), ()]
res = [t for i, t in enumerate(tuples) if t]
print(res)

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ('', '')]


In [ ]:
#Program to print duplicates from a list of integers
lis = [1, 2, 1, 2, 3, 4, 5, 1, 1, 2, 5, 6, 7, 8, 9, 9]
uniqueList = []
duplicateList = []
for i in lis:
  if i not in uniqueList:
    uniqueList.append(i)
  elif i not in duplicateList:
    duplicateList.append(i)
print(duplicateList)

[1, 2, 5, 9]


In [ ]:
#2
list = [1, 2, 1, 2, 3, 4, 5, 1, 1, 2, 5, 6, 7, 8, 9, 9]
new = []
for a in list:
  n = list.count(a)
if n > 1:
  if new.count(a) == 0:
    new.append(a)
print(new)

[9]


In [ ]:
#find Cumulative sum of a list
list = [10,20,30,40,50]
new_list = []
j=0
for i in range(0,len(list)):
  j+=list[i]
  new_list.append(j)
print(new_list)

[10, 30, 60, 100, 150]


In [ ]:
#Sum of number digits in List
test_list = [12, 67, 98, 34]
test_list = [12,17,23,53]
print("the original list is : " + str(test_list))
res = []
for ele in test_list:
  sum = 0
  for digit in str(ele):
    sum += int(digit)
  res.append(sum)
print("list integer summation : " + str(res))

the original list is : [12, 17, 23, 53]
list integer summation : [3, 8, 5, 8]


In [ ]:
#Break a list into chunks of size N in Python
my_list = [1, 2, 3, 4, 5,
           6, 7, 8, 9]
start = 0
end = len(my_list)
step = 3
for i in range(start, end, step):
    x = i
    print(my_list[x:x+step])

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [ ]:
#Sort the values of first list using second list in Python
# Python program to sort values of first list based on second list
from collections import OrderedDict
list1 = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
list2 = [0, 1, 1, 0, 1, 2, 2, 0, 1]
d = OrderedDict(zip(list1, list2))
res = list(OrderedDict(sorted(d.items(), key=lambda x: x[1])))
print(res)

TypeError: ignored

# Matrix Programs:

In [ ]:
#Python program to add two Matrices
## Program to add two matrices using nested loop

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
 
result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
# iterate through rows
for i in range(len(X)):  
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
 
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [ ]:
#Python program to multiply two matrices
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
for i in range(len(A)):# iterating by row of A
  for j in range(len(B[0])):# iterating by column by B
    for k in range(len(B)):# iterating by rows of B
      result[i][j] += A[i][k] * B[k][j]
      for r in result:
        print(r)
       
      
 

[60, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[102, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 96, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 145, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 12, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 33, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 24]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 24]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[0, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[20, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[50, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 0, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 32, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 67, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 0, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 4, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 19, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 73, 0]
[0, 0, 0, 0]
[114, 160, 60, 27]
[74, 97, 73, 8]
[0, 0, 0, 0]
[114, 160, 60

In [ ]:
#Matrix Product
test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
print("The original list: " + str(test_list))
x = []
for i in test_list:
  x.extend(i)
res = 1
for j in x:
  res *= j
print("the total element product in lists is : " + str(res))

The original list: [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
the total element product in lists is : 1622880


In [ ]:
#Adding and Subtracting Matrices in Python
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
print("printing elements of first matrix")
print(a)
print("printing elements of second matix")
print(b)
print("adding of two matrix")
print(np.add(a,b))


printing elements of first matrix
[[1 2]
 [3 4]]
printing elements of second matix
[[4 5]
 [6 7]]
adding of two matrix
[[ 5  7]
 [ 9 11]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
print("printing elements of first matrix")
print(a)
print("printing elements of second matix")
print(b)
print("subtraction of two matrix")
print(np.subtract(a,b))

printing elements of first matrix
[[1 2]
 [3 4]]
printing elements of second matix
[[4 5]
 [6 7]]
subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [ ]:
#Transpose a matrix in Single line in Python
import numpy
matrix = [[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Matrix creation of n*n
n = 4
print("The dimension: " + str(n))
res = []
for i in range(n):
  row =[]
  for j in range(n):
    row.append(1+n*i+j)
  res.append(row)
print("The created matrix of n*n:"+str(res))

The dimension: 4
The created matrix of n*n:[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
#Get Kth Column of Matrix
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
print("The original list is: " + str(test_list))
k = 2
res = [sub[k] for sub in test_list]
print("the kth columnb of matrix is:" + str(res))

The original list is: [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
the kth columnb of matrix is:[6, 10, 5]


In [ ]:
#Vertical Concatenation in Matrix
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
print("the original list : " + str(test_list))
res = []
n = 0
while n != len(test_list):
  temp = ''
  for idx in test_list:
    try: temp = temp + idx[n]
    except IndexError: pass
  res.append(temp)
  n = n+1
res = [ele for ele in res if ele]
print("list after column concatentation: " + str(res))


the original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
list after column concatentation: ['GfgisBest', 'goodfor']


# **String**

In [ ]:
#Python program to check if a string is palindrome or not
x = "malayalam"
w = ""
for i in x:
  w = i+w
if (x == w):
  print("yes")
else:
  print("no")

yes


In [ ]:
def isPalindrome(s):
  return s == s[::-1]
s = "malayalam"
ans = isPalindrome(s)
if ans:
  print("yes")
else:
  print("no")
  

yes


In [ ]:
#Python program to check whether the string is Symmetrical or Palindrome
string = 'amaama'
half = int(len(string)/2)
first_str = string[:half]
second_str = string[half:]

if first_str == second_str:
  print(string, 'string is symmetrical')
else:
  print(string, 'string is not symmetrical')
if first_str == second_str[::-1]:# join(reversed(second_str))
  print(string, 'string is palindrome')
else:
  print(string, 'string is not palindrome')

amaama string is symmetrical
amaama string is palindrome


In [ ]:
#Reverse words in a given String in Python
string = "geeks quiz practice code"
stack = []
for word in string.split():
  stack.append(word)
reversed_words = []
while stack:
  reversed_words.append(stack.pop())
reversed_string = " ".join(reversed_words)
print(reversed_string)

code practice quiz geeks


In [ ]:
#Ways to remove i’th character from string in Python
test_str = "Geaksforgeeks"
new_str = ""
for i in range(len(test_str)):
  if i != 2:
    new_str = new_str + test_str[i]
print("the string after removal of i'th character :" + new_str)

the string after removal of i'th character :a


In [ ]:
#Check if a Substring is Present in a Given String
myst = "A geek in need is a geek indeed"
if "need" in myst:
  print("yes! it is present in the string")
else:
  print("no! it is not present")

yes! it is present in the string


In [ ]:
# Words Frequency in String Shorthands
string=" This tutorial for Python tutorial"
print(string) 

# dictionary and count() and split()
word= {key: string.count(key) for key in string.split()}

# print result
print("Words in the string")
print(word)

 This tutorial for Python tutorial
Words in the string
{'This': 1, 'tutorial': 2, 'for': 1, 'Python': 1}


In [ ]:
#Convert Snake case to Pascal case
string= "program_tutorial"
print("Snake case: ",string)
pascal= string.replace('_',' ').title()
pascal= pascal.replace(' ','')
print("Pascal case: ",pascal)


Snake case:  program_tutorial
Pascal case:  ProgramTutorial


In [ ]:
#Find length of a string in python 6 ways
str = "Neha"
print(len(str))

4


In [ ]:
#2
def findlen(str):
  counter = 0
  for i in str:
    counter += 1
  return counter
str = "Shivam"
print((findlen(str)))

6


In [ ]:
#3
string = "Shivam Pathak"
s = 0
for i, a in enumerate(string):
  s += 1
print(s)

13


In [ ]:
#Program to accept the strings which contains all vowels
def check(string):
  strng = string.lower()
vowels = set("aeiou")
s = set({})
for char in string:
  if char in vowels:
    s.add(char)
  else:
    pass
if len(s) == len(vowels):
  print("accepted")
else:
  print("not accepted")


 

   

not accepted


In [ ]:
#
# Function for check if string
# is accepted or not
 
#using all() method
 
def check(string):
    vowels = "aeiou" #storing vowels
    if all(vowel in string.lower() for vowel in vowels):
        return "Accepted"
    return "Not accepted"
 
 
 
#initializing string
string = "SEEquoiaL"
# test the function
print(check(string))

Accepted


In [ ]:
#Count the Number of matching characters in a pair of string
# Python code to count number of unique matching
 
def count(s1, s2):
    c=0 #counter variable
    j=0
    for i in s1:
        if s2.find(i)>-0 and j==s1.find(i):
            c=c+1
        j=j+1
    print("Matching char: ",c)

s1="aabcdefk12"
s2="b2acdefk1"
count(s1,s2)
    

Matching char:  8


In [ ]:
from IPython.core.interactiveshell import removed_co_newlocals
#Remove all duplicates from a given string in Python
def removeDuplicate(str):
  s=set(str)
  s="".join(s)
  print("without order:",s)
  t=""
  for i in str:
    if(i in t):
      pass
    else:
      t=t+i
    print("with order:",t)
str = "geeks for geeks"
removeDuplicate(str)

without order: ersog kf
with order: g
with order: ge
with order: ge
with order: gek
with order: geks
with order: geks 
with order: geks f
with order: geks fo
with order: geks for
with order: geks for
with order: geks for
with order: geks for
with order: geks for
with order: geks for
with order: geks for


In [ ]:
# Least Frequent Character in String
test_str = "geeksforgeeks"
print("the original string is:" +test_str)
all freq = {}
for i in test_str:
  if i in all_freq:
    all_freq[i] += 1
  else:
    all_freq[i] = 1
res = min(all_freq, key = all_freq.get)
print("the minimum of all characters in geeksforgeeks is :" + str(res))


SyntaxError: ignored